# Generated by Django 5.0.6 on 2024-06-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='max_storage',
            field=models.IntegerField(null=True),
        ),
    ]
