# Generated by Django 5.0.6 on 2024-06-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_email_user_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
