# Generated by Django 5.0.6 on 2024-06-18 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.TextField()),
                ('folder_name', models.TextField(max_length=100)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='users.user_profile')),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_folder', to='dashboard.folder')),
            ],
        ),
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('file_id', models.TextField()),
                ('file_visibleName', models.TextField(max_length=100)),
                ('file_Name', models.TextField(max_length=100)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='users.user_profile')),
                ('parent_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_files', to='dashboard.folder')),
            ],
        ),
        migrations.CreateModel(
            name='master_folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.TextField()),
                ('folder_name', models.TextField(max_length=100)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='root_folder', to='users.user_profile')),
            ],
        ),
    ]
