# Generated by Django 5.0.6 on 2024-06-07 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('users', '0003_alter_user_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_of_folder', to='users.user_profile'),
        ),
        migrations.AlterField(
            model_name='master_folder',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_user', to='users.user_profile'),
        ),
    ]
