# Generated by Django 5.0.6 on 2024-06-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_Name',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='file_visibleName',
            new_name='file_visible_name',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
