# Generated by Django 5.0.6 on 2024-06-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_folder_user_alter_master_folder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='folder_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='master_folder',
            name='folder_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
