# Generated by Django 5.0.6 on 2024-06-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_folder_folder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='folder_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='master_folder',
            name='folder_id',
            field=models.TextField(),
        ),
    ]
