# Generated by Django 5.0.6 on 2024-06-07 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_folder_folder_id_alter_master_folder_folder_id'),
        ('users', '0003_alter_user_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_folder', to='users.user_profile'),
        ),
        migrations.AlterField(
            model_name='master_folder',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_folder', to='users.user_profile'),
        ),
    ]
