# Generated by Django 5.0.6 on 2024-06-11 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_master_folder_user'),
        ('users', '0003_alter_user_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to='users.user_profile'),
        ),
    ]
