# Generated by Django 5.0.6 on 2024-06-12 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_folder_user'),
        ('users', '0003_alter_user_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='users.user_profile'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_folder', to='dashboard.folder'),
        ),
    ]
